name: brim_map_simulator
description: A library for simulating map routes and handling polylines in a Dart/Flutter application.
version: 1.0.0
homepage: https://github.com/VenbrinoDevelopers/brim-map-simulator  
repository: https://github.com/VenbrinoDevelopers/brim-map-simulator  
issues: https://github.com/VenbrinoDevelopers/brim-map-simulator/issues 
topics: [googlemaps, polylines,simulater,flutter,dart] 

environment:
  sdk: ">=2.14.0 <4.0.0"


dev_dependencies:
  lints: ^4.0.0  
  test: ^1.24.0  
  mocktail: ^1.0.4  


